#!/bin/bash
#
# Title:      rTorrent + Rutorrent + Flood + Autodl + Pyrocore + rtControl
# Author(s):  Admin9705 & Clownfused
# URL:        https://pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

# FACTS #######################################################################

  - name: "Set Known Facts"
    set_fact:
      pgrole: "rutorrent-pyrocore"
      intport: "80"
      extport: "5898"
      intport2: "3000"
      extport2: "3000"
      intport3: "5000"
      extport3: "5000"
      intport4: "51415"
      extport4: "51415"
      image: "rutorrent-pyrocore:dev"
    
# CORE (MANDATORY) ############################################################
  - name: 'Including cron job'
    include_tasks: '/opt/communityapps/apps/_core.yml'

  - name: 'Including plugins'
    include_tasks: '/opt/communityapps/apps/_plugins.yml'
  
  - name: 'Including folders'
    include_tasks: '/opt/communityapps/apps/_downloaders.yml'
        
  - name: 'Ini Check'
    stat:
      path: /opt/appdata/{{pgrole}}/core.conf
    register: inicheck

# LABELS ######################################################################

  - name: "Setting PG Labels"
    set_fact:
      pg_labels:
        traefik.enable: "true"
        traefik.port: "{{intport}}"
        traefik.frontend.rule: "Host:{{pgrole}}.{{domain.stdout}},{{tldset}},rut.{{domain.stdout}},{{tldset}}"

  - name: "Setting PG Volumes"
    set_fact:
      pg_volumes:
        - "/opt/appdata/{{pgrole}}:/config"
        - '{{path.stdout}}:{{path.stdout}}'
        - '/mnt:/mnt'
        - '/mnt/unionfs:/unionfs'
        - '/mnt/downloads/{{pgrole}}:/downloads/complete'
        - '/mnt/incomplete/{{pgrole}}:/downloads/incomplete'
        - "/etc/localtime:/etc/localtime:ro"

  - name: "Setting PG ENV"
    set_fact:
      pg_env:
        PUID: 1000
        PGID: 1000

# MAIN DEPLOYMENT #############################################################

  - name: "Deploying Container - {{pgrole}}"
    docker_container:
      name: "rutorrent-pyrocore"
      state: present
      load_path: ~/rutorrent-pyrocore.dev.tar.gz
      tag: dev
      
      pull: no
      published_ports:
        - '{{extport}}:{{intport}}'
        - '{{ports.stdout}}{{extport2}}:{{intport2}}'
        - '{{ports.stdout}}{{extport3}}:{{intport3}}'
        - '{{ports.stdout}}{{extport4}}:{{intport4}}'
      volumes: "{{pg_volumes}}"
      env: "{{pg_env}}"
      restart_policy: always
      networks:
        - name: plexguide
          aliases:
            - "{{pgrole}}"
      state: started
      labels: "{{pg_labels}}"
